### ISSUE TITLE
your approaches doesn't work

### ISSUE THREAD

**Issue by ghost** [SBasalaev/alchemy-os#7]
you have said Open the file "/cfg/pkg/sources" and change http://alchemy-os.org to http://alchemy-os.sourceforge.net/.but that doesn't work I hope you can update alchemy-os to a right version which can refresh lists correctly

**Comment by SBasalaev** [comment]
Duplicate of #6

**Comment by SBasalaev** [comment]
Sorry, Alchemy OS is abandoned since 2014, I don't publish any more updates. You can still try to download packages from http://alchemy-os.sourceforge.net/packages/2.1/ and install them by hand.
The command is (if I remember correctly)
```
pkg-arh install yourfile.pkg
```
